### ISSUE TITLE
Undefined symbols for architecture when building with ionic

### ISSUE THREAD

**Issue by ajcrites** [urbanairship/phonegap-ua-push#193]
```
$ ionic info

Your system information:

Cordova CLI: 6.5.0
Ionic Framework Version: 2.3.0
Ionic CLI Version: 2.2.3
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.1.4
ios-deploy version: 1.9.1
ios-sim version: 6.0.0
OS: macOS Sierra
Node Version: v7.10.1
Xcode version: Xcode 8.2.1 Build version 8C1002
```

I can install the plugin fine with `cordova plugin add urbanairship-cordova`. When I do `ionic build ios` I consistently get an error that looks like:

```Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_SKStoreReviewController", referenced from:
      objc-class-ref in libUAirship-8.5.2.a(UARateAppAction.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

It's not always `x86_64`; I've seen it with `i386`. This will occur with a bare bones project using ionic such as https://github.com/ajcrites/ionic-ua-brk

**Comment by rlepinski** [comment]
@ajcrites Thanks for the report. Looking into it.

We did not run into this problem when we generated the project just from Cordova but we have an idea on what could be causing this. Ill update you when we have a fix.

**Comment by rlepinski** [comment]
@ajcrites We figured out the issue. We will release a patch on Tuesday after we do more internal testing. Thanks again for the report!

For now, you can probably work around the issue by adding:
```
#import <StoreKit/StoreKit.h>
```
to one of the .h files in the generated project or fallback to the previous version.

**Comment by sredeker** [comment]
@rlepinski, wanted to follow up and see if you are on track to complete this today? Please let us know an ETA so we can coordinate. Thanks!

**Comment by rlepinski** [comment]
@sredeker We are on track but it probably wont be released until end of day (pacific time).

**Comment by rlepinski** [comment]
Fixed in 6.9.1. Please reopen if you continue to have the issue.

**Comment by ajcrites** [comment]
@rlepinski I can't reopen but I'm still getting this issue with the plugin version 6.9.1

```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_SKStoreReviewController", referenced from:
      objc-class-ref in libUAirship-8.5.3.a(UARateAppAction.o)
ld: symbol(s) not found for architecture x86_64```

**Comment by rlepinski** [comment]
@ajcrites It works for me with a brand new project. Could you try wiping your derived data and building again?  `rm -rf ~/Library/Developer/Xcode/DerivedData/`

**Comment by rlepinski** [comment]
@ajcrites I just realized you are building with Xcode 8.2,  SKStoreReviewController was introduced in iOS 10.3 so it probably requires Xcode 8.3. Could you try updating your Xcode as well?
